### PR TITLE
Fix how recursive generic Windows Runtime types are unprojected

### PR DESCRIPTION
**Pull request by ignas2**

### CODE REVIEW

**Comment by joshpeterson** [comment]
@ignas2 Can we merge this change and https://github.com/Unity-Technologies/cecil/pull/7 before landing this in IL2CPP code?

**Comment by TautvydasZilys** [comment]
@joshpeterson We're actually still in discussion over slack whether this is a correct change.

**Comment by joshpeterson** [comment]
Ok, we'll wait on landing anything into the IL2CPP repo until we get these sorted out. I just want to avoid making two commits of the Cecil binaries if we can make one.

**Comment by ignas2** [comment]
@TautvydasZilys explained how this is supposed to work and I've reverted my changes. Keeping the test though. Cecil binaries thus won't be affected and I won't push anything to IL2CPP repo.

**Comment by TautvydasZilys** [comment]
LTGM.

**Pull request merged**
